package main

import (
	"encoding/json"
	"net/http"
	"os"
	"path/filepath"
	"testing"
)

// makeValidPair returns a fresh, valid X25519 Reality keypair for crafting
// node.json fixtures.
func makeValidPair(t *testing.T) (priv, pub string) {
	t.Helper()
	priv, pub, err := generateRealityKeypair()
	if err != nil {
		t.Fatal(err)
	}
	return priv, pub
}

func nodeWithKeys(t *testing.T, dir string, tlsJSON string) {
	writeStateFile(t, dir, "node.json", `{
  "version": 1,
  "node": {"id": 1, "name": "n1", "type": "vless", "enabled": true},
  "auth": {"token": "T"},
  "server": {"listen": "0.0.0.0", "port": 443},
  "tls": `+tlsJSON+`,
  "runtime": {"sync_interval": 60, "traffic_flush_interval": 300}
}`)
	writeStateFile(t, dir, "users.json", `{"version":1,"users":[]}`)
}

func newRealityStore(t *testing.T, tlsJSON string) *Store {
	t.Helper()
	dir := t.TempDir()
	nodeWithKeys(t, dir, tlsJSON)
	s, err := NewStore(dir)
	if err != nil {
		t.Fatalf("NewStore: %v", err)
	}
	return s
}

// G2 matrix 1: empty private_key -> auto-generate a valid pair.
func TestRealityKeypairAutoGeneratedAndPersisted(t *testing.T) {
	s := newRealityStore(t, `{"enabled":true,"server_name":"www.microsoft.com","server_port":443}`)
	e, _ := s.lookupNode(1)
	if e.TLS.PrivateKey == "" || e.TLS.PublicKey == "" {
		t.Fatalf("keypair not generated: priv=%q pub=%q", e.TLS.PrivateKey, e.TLS.PublicKey)
	}
	if !validRealityKey(e.TLS.PrivateKey) || !validRealityKey(e.TLS.PublicKey) {
		t.Fatal("generated keys are not valid 32-byte base64url X25519 keys")
	}
	derived, err := deriveRealityPublicKey(e.TLS.PrivateKey)
	if err != nil || derived != e.TLS.PublicKey {
		t.Fatalf("public_key must equal derive(private_key): derived=%q err=%v", derived, err)
	}
	// Persisted on disk (atomic write).
	var nf NodeFile
	raw, err := os.ReadFile(filepath.Join(s.dir, "node.json"))
	if err != nil {
		t.Fatal(err)
	}
	if err := json.Unmarshal(raw, &nf); err != nil {
		t.Fatal(err)
	}
	if nf.TLS.PrivateKey != e.TLS.PrivateKey || nf.TLS.PublicKey != e.TLS.PublicKey {
		t.Fatalf("keypair not persisted: file=%+v", nf.TLS)
	}
}

// G2 matrix 0: first boot on an EMPTY directory must generate AND persist the
// keypair (fresh-creation path in loadSingleNode, not just the file-load path).
func TestRealityKeypairGeneratedOnFirstBoot(t *testing.T) {
	dir := t.TempDir()
	s, err := NewStore(dir)
	if err != nil {
		t.Fatalf("NewStore(empty dir): %v", err)
	}
	e, _ := s.lookupNode(1)
	if e.TLS.PrivateKey == "" || e.TLS.PublicKey == "" {
		t.Fatalf("first boot did not generate keypair: priv=%q pub=%q", e.TLS.PrivateKey, e.TLS.PublicKey)
	}
	if !validRealityKey(e.TLS.PrivateKey) || !validRealityKey(e.TLS.PublicKey) {
		t.Fatal("first-boot generated keys are not valid 32-byte base64url X25519 keys")
	}
	// Persisted: a second store load must reuse the SAME keys (no regeneration).
	var nf NodeFile
	raw, err := os.ReadFile(filepath.Join(dir, "node.json"))
	if err != nil {
		t.Fatal(err)
	}
	if err := json.Unmarshal(raw, &nf); err != nil {
		t.Fatal(err)
	}
	if nf.TLS.PrivateKey != e.TLS.PrivateKey || nf.TLS.PublicKey != e.TLS.PublicKey {
		t.Fatalf("first-boot keypair not persisted: file=%+v", nf.TLS)
	}
	s2, err := NewStore(dir)
	if err != nil {
		t.Fatalf("second NewStore: %v", err)
	}
	e2, _ := s2.lookupNode(1)
	if e2.TLS.PrivateKey != e.TLS.PrivateKey || e2.TLS.PublicKey != e.TLS.PublicKey {
		t.Fatalf("keypair regenerated across restarts: before=%q/%q after=%q/%q",
			e.TLS.PrivateKey, e.TLS.PublicKey, e2.TLS.PrivateKey, e2.TLS.PublicKey)
	}
}

// G2 matrix 2 & 3: /config includes private_key and public_key.
func TestRealityConfigIncludesKeys(t *testing.T) {
	s := newRealityStore(t, `{"enabled":true}`)
	e := newAPIEnv(t, s)
	resp, body := e.get(t, "/api/v1/server/UniProxy/config", e.token, "1", "vless")
	if resp.StatusCode != http.StatusOK {
		t.Fatalf("status = %d body=%s", resp.StatusCode, body)
	}
	var cfg map[string]any
	if err := json.Unmarshal(body, &cfg); err != nil {
		t.Fatal(err)
	}
	ts, ok := cfg["tls_settings"].(map[string]any)
	if !ok {
		t.Fatalf("tls_settings missing: %s", body)
	}
	priv, _ := ts["private_key"].(string)
	pub, _ := ts["public_key"].(string)
	if priv == "" || pub == "" {
		t.Fatalf("config missing reality keys: %s", body)
	}
	if !validRealityKey(priv) || !validRealityKey(pub) {
		t.Fatalf("config keys invalid format: %s", body)
	}
	if derived, _ := deriveRealityPublicKey(priv); derived != pub {
		t.Fatalf("config public_key != derive(private_key): %s", body)
	}
}

// G2 matrix 4 & 5: restart -> the exact same keypair (never regenerated).
func TestRealityKeypairStableAcrossRestarts(t *testing.T) {
	dir := t.TempDir()
	nodeWithKeys(t, dir, `{"enabled":true}`)
	s1, err := NewStore(dir)
	if err != nil {
		t.Fatal(err)
	}
	e1, _ := s1.lookupNode(1)
	priv1, pub1 := e1.TLS.PrivateKey, e1.TLS.PublicKey

	s2, err := NewStore(dir)
	if err != nil {
		t.Fatal(err)
	}
	e2, _ := s2.lookupNode(1)
	if e2.TLS.PrivateKey != priv1 || e2.TLS.PublicKey != pub1 {
		t.Fatalf("keypair changed across restart: %q/%q -> %q/%q", priv1, pub1, e2.TLS.PrivateKey, e2.TLS.PublicKey)
	}
}

// G2 matrix 6: deleting the keypair from node.json -> a fresh pair is generated.
func TestRealityKeypairRegeneratedWhenDeleted(t *testing.T) {
	dir := t.TempDir()
	nodeWithKeys(t, dir, `{"enabled":true}`)
	s1, err := NewStore(dir)
	if err != nil {
		t.Fatal(err)
	}
	e1, _ := s1.lookupNode(1)
	priv1 := e1.TLS.PrivateKey

	var nf NodeFile
	raw, _ := os.ReadFile(filepath.Join(dir, "node.json"))
	if err := json.Unmarshal(raw, &nf); err != nil {
		t.Fatal(err)
	}
	nf.TLS.PrivateKey = ""
	nf.TLS.PublicKey = ""
	out, _ := json.Marshal(nf)
	if err := os.WriteFile(filepath.Join(dir, "node.json"), out, 0600); err != nil {
		t.Fatal(err)
	}

	s2, err := NewStore(dir)
	if err != nil {
		t.Fatal(err)
	}
	e2, _ := s2.lookupNode(1)
	if e2.TLS.PrivateKey == "" {
		t.Fatal("expected a fresh keypair")
	}
	if e2.TLS.PrivateKey == priv1 {
		t.Fatal("expected a fresh keypair, got the old one")
	}
}

// G2 matrix 7: only a private_key configured -> public_key derived and saved.
func TestRealityPublicKeyDerivedFromPrivateOnly(t *testing.T) {
	priv, wantPub := makeValidPair(t)
	tlsJSON, _ := json.Marshal(map[string]any{
		"enabled": true, "server_name": "www.microsoft.com", "private_key": priv,
	})
	s := newRealityStore(t, string(tlsJSON))
	e, _ := s.lookupNode(1)
	if e.TLS.PrivateKey != priv {
		t.Fatal("user-configured private_key must never be overwritten")
	}
	if e.TLS.PublicKey != wantPub {
		t.Fatalf("public_key = %q, want derived %q", e.TLS.PublicKey, wantPub)
	}
	var nf NodeFile
	raw, _ := os.ReadFile(filepath.Join(s.dir, "node.json"))
	if err := json.Unmarshal(raw, &nf); err != nil {
		t.Fatal(err)
	}
	if nf.TLS.PublicKey != wantPub {
		t.Fatalf("derived public_key not persisted: %+v", nf.TLS)
	}
}

// G2 matrix 9: user-configured matching keypair is kept untouched.
func TestRealityUserKeypairKept(t *testing.T) {
	priv, pub := makeValidPair(t)
	tlsJSON, _ := json.Marshal(map[string]any{"enabled": true, "private_key": priv, "public_key": pub})
	s := newRealityStore(t, string(tlsJSON))
	e, _ := s.lookupNode(1)
	if e.TLS.PrivateKey != priv || e.TLS.PublicKey != pub {
		t.Fatalf("user keypair was modified: priv=%q pub=%q", e.TLS.PrivateKey, e.TLS.PublicKey)
	}
}

// G2 matrix 8: mismatched keypair -> clear refusal, never a wrong config.
func TestRealityKeypairMismatchRefusesStartup(t *testing.T) {
	priv, _ := makeValidPair(t)
	_, otherPub := makeValidPair(t)
	dir := t.TempDir()
	nodeWithKeys(t, dir, `{"enabled":true,"private_key":"`+priv+`","public_key":"`+otherPub+`"}`)
	if _, err := NewStore(dir); err == nil {
		t.Fatal("expected startup refusal on mismatched reality keypair")
	}
}

// Invalid private_key format -> refusal.
func TestRealityInvalidPrivateKeyRefusesStartup(t *testing.T) {
	dir := t.TempDir()
	nodeWithKeys(t, dir, `{"enabled":true,"private_key":"not-a-key"}`)
	if _, err := NewStore(dir); err == nil {
		t.Fatal("expected startup refusal on malformed reality private_key")
	}
}

// public_key without private_key -> refusal (cannot be served or derived).
func TestRealityPublicKeyWithoutPrivateRefusesStartup(t *testing.T) {
	_, pub := makeValidPair(t)
	dir := t.TempDir()
	nodeWithKeys(t, dir, `{"enabled":true,"public_key":"`+pub+`"}`)
	if _, err := NewStore(dir); err == nil {
		t.Fatal("expected startup refusal on public_key without private_key")
	}
}

// Multi-node: only vless/both entries get Reality keypairs; hy2 is untouched.
func TestRealityKeypairMultiNodeNodesJSON(t *testing.T) {
	dir := t.TempDir()
	writeStateFile(t, dir, "nodes.json", `{"version":1,"token":"T","nodes":[
  {"id":1,"type":"vless","enabled":true,"server":{"listen":"0.0.0.0","port":443}},
  {"id":2,"type":"hy2","enabled":true,"server":{"listen":"0.0.0.0","port":44311}},
  {"id":3,"type":"both","enabled":true,"server":{"listen":"0.0.0.0","port":8443}}
]}`)
	writeStateFile(t, dir, "users.json", `{"version":1,"users":[]}`)
	s, err := NewStore(dir)
	if err != nil {
		t.Fatal(err)
	}
	e1, _ := s.lookupNode(1)
	e2, _ := s.lookupNode(2)
	e3, _ := s.lookupNode(3)
	if e1.TLS.PrivateKey == "" || e3.TLS.PrivateKey == "" {
		t.Fatal("vless/both nodes must get Reality keypairs")
	}
	if e2.TLS.PrivateKey != "" || e2.TLS.PublicKey != "" {
		t.Fatal("hy2 node must not get Reality keys")
	}
	// Persisted for all nodes.
	var nf NodesFile
	raw, _ := os.ReadFile(filepath.Join(dir, "nodes.json"))
	if err := json.Unmarshal(raw, &nf); err != nil {
		t.Fatal(err)
	}
	if nf.Nodes[0].TLS.PrivateKey != e1.TLS.PrivateKey || nf.Nodes[2].TLS.PrivateKey != e3.TLS.PrivateKey {
		t.Fatal("multi-node keypairs not persisted")
	}
}

// G2 matrix 2 for hy2 config: must NOT contain reality keys (protocol shape).
func TestRealityConfigHy2HasNoKeys(t *testing.T) {
	dir := t.TempDir()
	writeStateFile(t, dir, "nodes.json", `{"version":1,"token":"T","nodes":[
  {"id":2,"type":"hy2","enabled":true,"server":{"listen":"0.0.0.0","port":44311}}
]}`)
	writeStateFile(t, dir, "users.json", `{"version":1,"users":[]}`)
	s, err := NewStore(dir)
	if err != nil {
		t.Fatal(err)
	}
	e := newAPIEnv(t, s)
	resp, body := e.get(t, "/api/v1/server/UniProxy/config", "T", "2", "hysteria")
	if resp.StatusCode != http.StatusOK {
		t.Fatalf("status = %d body=%s", resp.StatusCode, body)
	}
	if _, ok := bodyContainsKey(body); ok {
		t.Fatalf("hy2 config must not contain reality keys: %s", body)
	}
}

func bodyContainsKey(body []byte) (string, bool) {
	var cfg map[string]any
	if err := json.Unmarshal(body, &cfg); err != nil {
		return "", false
	}
	ts, ok := cfg["tls_settings"].(map[string]any)
	if !ok {
		return "", false
	}
	if k, ok := ts["private_key"].(string); ok && k != "" {
		return "private_key", true
	}
	if k, ok := ts["public_key"].(string); ok && k != "" {
		return "public_key", true
	}
	return "", false
}
